Validate custom license length.
poggit/poggit pull request #205
Opened 2020-01-19 15:12 UTC by JaxkDev

Fairly self explanatory, majority of plugins submitted have no license by taking advantage of custom license option and leaving it blank.
(This is left blank when poggit finds no LICENSE file as well)

PR adds a length check if license is custom, it check against < 200char (200 because the smallest OSL license i could find was the Fair license which *without user details* measures in at about 206).

2020-01-19 15:33 UTC, SOF3 requested changes
How about validation at client side?

2020-01-19 15:33 UTC, SOF3 commented on src/poggit/release/submit/PluginSubmission.php
> +                throw new SubmitException("Custom license's must be under an open source license, and the full text of the license is required.");
what's up with the apostrophe here?

2020-01-19 15:34 UTC, JaxkDev commented
Ok

2020-01-19 17:30 UTC, JaxkDev commented
Tested custom license of < 200 chars, above 200 and non-custom licenses.

2020-01-20 00:49 UTC, SOF3 commented
Is closer compiler doing something fishy? The diff seemed to contain something irrelevant.

2020-01-20 16:11 UTC, JaxkDev commented on js/newSubmit.min.js
> +200>this.getValue().custom.length?{valid:!1,message:"The custom license must be a open source license, and the full text is required."}:{valid:!0}}));g.push(new k("perms",f.fields.perms,"Permissions"
When removing my code (back to original js only this is removed rest of changes persist.

2020-01-20 17:35 UTC, merged