Clears the bright display.
poggit/poggit pull request #358
Opened 2024-11-20 15:16 UTC by KnosTx

2024-11-20 15:20 UTC, JaxkDev requested changes, later dismissed
~~Commit 3f04d88e133401357aa655969439b2bb97a53dfe needs to be minified I'm assuming it was not included.~~

2024-11-20 15:49 UTC, JaxkDev commented
Is the blue bar intentional ?

2024-11-20 15:59 UTC, JaxkDev commented
Here are some of the differences I can spot off the bat, everyones input is welcome.

Will probably give it a week or two before looking at merging if no problems from others is commented below.

--

**Original    ||     New (PR)**

Change in footer:
![image](https://github.com/user-attachments/assets/08459e0c-71b3-4e44-ab8e-cfdac1591c8a)

Change in icon alignment in submission form:
![image](https://github.com/user-attachments/assets/2c59eab9-1999-4f0a-a450-cd61909587db)

'Boxed' main body in all pages:
![image](https://github.com/user-attachments/assets/8c12d054-c52f-4405-85a2-468f55708f8c)

Cleaner scroller and slightly more padded tables:
![image](https://github.com/user-attachments/assets/62091da1-b6e7-4bc6-b7e2-de585d8b420c)

2024-11-23 10:10 UTC, KnosTx commented
I have fixed it so that the blue bar and blue text do not appear in the header navbar.

2024-12-06 23:15 UTC, ClousCloud commented
It looks good.

2025-07-27 11:16 UTC, ItzxDwi approved these changes

2025-08-02 06:16 UTC, closed without merging